"""Canonical Lead schema — single source of truth for the Hermes Leads Assistant.

The `leads` and `lead_events` tables are defined here as plain data so that
both the Python plugins (lead-capture, lead-dashboard) and the TypeScript
portal can derive their types from the same definition.

TS side consumes this via the JSON Schema emitted by `emit_json_schema()`
(see `packages/shared/schemas/lead.json`, regenerated by the contract test
`tests/contract/test_emit_schema.py`). Drift between this file and the TS
`Lead` interface is caught by `apps/portal/tests/contract/lead-schema.test.ts`.

Keep this file boring and dependency-free: no Pydantic, no attrs, just plain
tuples and dicts. It has to import cleanly from inside the Hermes plugin
venv and from CI runners.
"""

from __future__ import annotations

# ---- Enums (must match db.py + apps/portal/src/lib/schemas.ts) ---------------

# Kanban columns assigned by the LLM extractor.
KANBAN_COLUMNS: list[str] = ["frio", "tibio", "caliente"]

# `descartado` is a manual-only state (operator discards from the portal).
# The extractor never assigns it, but it is a valid target for manual moves.
VALID_KANBAN_COLUMNS: list[str] = KANBAN_COLUMNS + ["descartado"]

VALID_TEMPERATURES: list[str] = KANBAN_COLUMNS  # same three values
VALID_URGENCIES: list[str] = ["low", "medium", "high"]
VALID_COLUMN_SOURCES: list[str] = ["llm", "manual"]
VALID_PLATFORMS: list[str] = ["telegram", "kapso", "web"]


# ---- Column definitions ------------------------------------------------------
# (name, sqlite_type, nullable, description). The portal's LeadRecord maps
# every one of these columns, so additions here must be reflected there.
LEADS_COLUMNS: list[dict[str, object]] = [
    {"name": "id", "sqlite_type": "TEXT", "nullable": False, "pk": True},
    {"name": "user_id", "sqlite_type": "TEXT", "nullable": False},
    {"name": "session_id", "sqlite_type": "TEXT", "nullable": True},
    {"name": "platform", "sqlite_type": "TEXT", "nullable": True, "enum": VALID_PLATFORMS},
    {"name": "name", "sqlite_type": "TEXT", "nullable": True},
    {"name": "email", "sqlite_type": "TEXT", "nullable": True},
    {"name": "phone", "sqlite_type": "TEXT", "nullable": True},
    {"name": "interest", "sqlite_type": "TEXT", "nullable": True},
    {"name": "urgency", "sqlite_type": "TEXT", "nullable": False, "default": "'medium'", "enum": VALID_URGENCIES},
    {"name": "temperature", "sqlite_type": "TEXT", "nullable": False, "default": "'tibio'", "enum": VALID_TEMPERATURES},
    {"name": "kanban_column", "sqlite_type": "TEXT", "nullable": False, "default": "'tibio'", "enum": VALID_KANBAN_COLUMNS},
    {"name": "position", "sqlite_type": "REAL", "nullable": False, "default": "0"},
    {"name": "summary", "sqlite_type": "TEXT", "nullable": True},
    {"name": "notes", "sqlite_type": "TEXT", "nullable": True},
    {"name": "last_user_message", "sqlite_type": "TEXT", "nullable": True},
    {"name": "last_assistant_message", "sqlite_type": "TEXT", "nullable": True},
    {"name": "raw_extraction", "sqlite_type": "TEXT", "nullable": True},
    {"name": "last_extracted_at", "sqlite_type": "TEXT", "nullable": True},
    {"name": "column_source", "sqlite_type": "TEXT", "nullable": False, "default": "'llm'", "enum": VALID_COLUMN_SOURCES},
    {"name": "column_locked_at", "sqlite_type": "TEXT", "nullable": True},
    {"name": "manual_override", "sqlite_type": "INTEGER", "nullable": False, "default": "0"},
    {"name": "created_at", "sqlite_type": "TEXT", "nullable": False},
    {"name": "updated_at", "sqlite_type": "TEXT", "nullable": False},
]

LEAD_EVENTS_COLUMNS: list[dict[str, object]] = [
    {"name": "id", "sqlite_type": "INTEGER", "nullable": False, "pk": True, "autoincrement": True},
    {"name": "lead_id", "sqlite_type": "TEXT", "nullable": False, "fk": "leads(id)"},
    {"name": "event_type", "sqlite_type": "TEXT", "nullable": False},
    {"name": "payload", "sqlite_type": "TEXT", "nullable": True},
    {"name": "created_at", "sqlite_type": "TEXT", "nullable": False},
]


def emit_json_schema() -> dict[str, object]:
    """Emit a JSON-Schema-ish description of the lead tables.

    Not a strict JSON Schema (we want enums and defaults), but a stable
    contract the TS side can introspect. Tests assert that every column here
    is present in the SQLite table and in the TS interface.
    """
    return {
        "$schema": "lead-ai-internal/v1",
        "tables": {
            "leads": {
                "columns": LEADS_COLUMNS,
                "unique": [["user_id", "platform"]],
            },
            "lead_events": {
                "columns": LEAD_EVENTS_COLUMNS,
                "unique": [],
            },
        },
        "enums": {
            "kanban_columns": VALID_KANBAN_COLUMNS,
            "temperatures": VALID_TEMPERATURES,
            "urgencies": VALID_URGENCIES,
            "platforms": VALID_PLATFORMS,
            "column_sources": VALID_COLUMN_SOURCES,
        },
    }


def column_names(table: str) -> list[str]:
    """Helper used by the contract test."""
    tables = emit_json_schema()["tables"]
    assert table in tables, f"unknown table: {table}"
    return [c["name"] for c in tables[table]["columns"]]  # type: ignore[index]
