"""Demo / migration seeds for catalog verticals."""

from __future__ import annotations

from typing import Any

# Seeded from examples/canova-cars/knowledge/inventario.md (source of truth migrates to SQLite).
CANOVA_AUTOS: list[dict[str, Any]] = [
    {
        "title": "Chevrolet Onix 1.0 Turbo LTZ",
        "status": "available",
        "price_amount": 28_500_000,
        "price_kind": "from",
        "summary": "0 km — ideal primer auto, ciudad, bajo consumo",
        "description": "Ideal para: primer auto, ciudad, bajo consumo.",
        "attrs": {
            "marca": "Chevrolet",
            "modelo": "Onix",
            "version": "1.0 Turbo LTZ",
            "anio": 2025,
            "km": 0,
            "condicion": "0km",
            "combustible": "Nafta",
            "transmision": "Manual 6 vel. / Automática CVT",
            "equipamiento": "Aire acondicionado, direccional eléctrica, pantalla multimedia 8\", cámara de retroceso, control de estabilidad, 6 airbags",
            "ideal_para": "primer auto, ciudad, bajo consumo",
        },
    },
    {
        "title": "Fiat Pulse 1.0 Turbo Impetus AT6",
        "status": "available",
        "price_amount": 31_200_000,
        "price_kind": "from",
        "summary": "0 km — familia, ciudad, confort",
        "description": "Ideal para: familia, ciudad, confort.",
        "attrs": {
            "marca": "Fiat",
            "modelo": "Pulse",
            "version": "1.0 Turbo Impetus AT6",
            "anio": 2025,
            "km": 0,
            "condicion": "0km",
            "combustible": "Nafta",
            "transmision": "Automática 6 vel.",
            "equipamiento": "Aire acondicionado, banner digital, pantalla 10.1\", wireless, comando de voz, asistentes de conducción, 6 airbags",
            "ideal_para": "familia, ciudad, confort",
        },
    },
    {
        "title": "Toyota Corolla Cross 1.8 Hi-Hybrid SEG",
        "status": "available",
        "price_amount": 42_800_000,
        "price_kind": "from",
        "summary": "0 km — familia, eficiencia, confiabilidad",
        "description": "Ideal para: familia, eficiencia, confiabilidad.",
        "attrs": {
            "marca": "Toyota",
            "modelo": "Corolla Cross",
            "version": "1.8 Hi-Hybrid SEG",
            "anio": 2025,
            "km": 0,
            "condicion": "0km",
            "combustible": "Híbrido",
            "transmision": "CVT",
            "equipamiento": "Aire acondicionado dual, Toyota Safety Sense, pantalla 8\", techo solar, sensor de estacionamiento, 7 airbags",
            "ideal_para": "familia, eficiencia, confiabilidad",
        },
    },
    {
        "title": "Volkswagen Taos 1.4 TSI Highline DSG",
        "status": "available",
        "price_amount": 39_500_000,
        "price_kind": "from",
        "summary": "0 km — familia, confort premium, ruta",
        "description": "Ideal para: familia, confort premium, ruta.",
        "attrs": {
            "marca": "Volkswagen",
            "modelo": "Taos",
            "version": "1.4 TSI Highline DSG",
            "anio": 2025,
            "km": 0,
            "condicion": "0km",
            "combustible": "Nafta",
            "transmision": "DSG 7 vel.",
            "equipamiento": "Aire acondicionado digital, App-Connect, IQ.Drive, faros LED, techo panorámico, asientos calefaccionados, 6 airbags",
            "ideal_para": "familia, confort premium, ruta",
        },
    },
    {
        "title": "Toyota Hilux SRV 2.8 CD 4x4 AT",
        "status": "available",
        "price_amount": 52_300_000,
        "price_kind": "from",
        "summary": "0 km — trabajo, campo, Adventure",
        "description": "Ideal para: trabajo, campo, Adventure.",
        "attrs": {
            "marca": "Toyota",
            "modelo": "Hilux",
            "version": "SRV 2.8 CD 4x4 AT",
            "anio": 2025,
            "km": 0,
            "condicion": "0km",
            "combustible": "Diésel",
            "transmision": "Automática 6 vel.",
            "equipamiento": "4x4 con reducida, pantalla multimedia, cámara de retroceso, control de tracción, frenos ABS, 7 airbags",
            "ideal_para": "trabajo, campo, Adventure",
        },
    },
    {
        "title": "Chevrolet S10 Z71 4x4 AT",
        "status": "available",
        "price_amount": 48_700_000,
        "price_kind": "from",
        "summary": "0 km — trabajo, Adventure, confort",
        "description": "Ideal para: trabajo, Adventure, confort.",
        "attrs": {
            "marca": "Chevrolet",
            "modelo": "S10",
            "version": "Z71 4x4 AT",
            "anio": 2025,
            "km": 0,
            "condicion": "0km",
            "combustible": "Diésel",
            "transmision": "Automática 6 vel.",
            "equipamiento": "4x4, suspensión deportiva, pantalla 8\", asientos de cuero, cámara 360°, sensor de estacionamiento",
            "ideal_para": "trabajo, Adventure, confort",
        },
    },
    {
        "title": "Renault Clio 1.6 Zen 2023",
        "status": "available",
        "price_amount": 18_900_000,
        "price_kind": "fixed",
        "summary": "Usado — 32.000 km, excelente",
        "description": "Estado: excelente, service oficial completo.",
        "attrs": {
            "marca": "Renault",
            "modelo": "Clio",
            "version": "1.6 Zen",
            "anio": 2023,
            "km": 32_000,
            "condicion": "usado",
            "equipamiento": "Aire acondicionado, dirección eléctrica, pantalla multimedia",
        },
    },
    {
        "title": "Ford EcoSport 1.5 Trend 2022",
        "status": "available",
        "price_amount": 21_500_000,
        "price_kind": "fixed",
        "summary": "Usado — 45.000 km, muy bueno",
        "description": "Estado: muy bueno, sin golpes.",
        "attrs": {
            "marca": "Ford",
            "modelo": "EcoSport",
            "version": "1.5 Trend",
            "anio": 2022,
            "km": 45_000,
            "condicion": "usado",
            "equipamiento": "Aire acondicionado, cámara de retroceso, Bluetooth",
        },
    },
    {
        "title": "Toyota Corolla 1.8 XEI 2021",
        "status": "available",
        "price_amount": 26_800_000,
        "price_kind": "fixed",
        "summary": "Usado — 58.000 km, excelente, único dueño",
        "description": "Estado: excelente, único dueño, service oficial.",
        "attrs": {
            "marca": "Toyota",
            "modelo": "Corolla",
            "version": "1.8 XEI",
            "anio": 2021,
            "km": 58_000,
            "condicion": "usado",
            "equipamiento": "Aire acondicionado dual, safety sense, pantalla 8\"",
        },
    },
]

DEMO_INMOBILIARIA: list[dict[str, Any]] = [
    {
        "title": "Depto 2 ambientes Palermo",
        "status": "available",
        "price_amount": 185_000,
        "price_currency": "USD",
        "price_kind": "fixed",
        "summary": "Venta — luminoso, balcón",
        "description": "Depto luminoso con balcón al frente. Ideal para inversión o primer vivienda.",
        "attrs": {
            "tipo": "depto",
            "operacion": "venta",
            "ambientes": 2,
            "m2": 48,
            "barrio": "Palermo",
            "ciudad": "CABA",
            "amenities": "Balcón, cocina integrada",
        },
    },
    {
        "title": "Casa 3 ambientes Vicente López",
        "status": "available",
        "price_amount": 320_000,
        "price_currency": "USD",
        "price_kind": "from",
        "summary": "Venta — jardín y garage",
        "description": "Casa con jardín y garage para 1 auto.",
        "attrs": {
            "tipo": "casa",
            "operacion": "venta",
            "ambientes": 3,
            "m2": 120,
            "barrio": "Vicente López",
            "ciudad": "GBA Norte",
            "amenities": "Jardín, garage",
        },
    },
]
