/**
 * Contract test — keeps the Python `leads` schema (source of truth) and the
 * TypeScript `Lead` interface in sync.
 *
 * Fails CI if:
 *   - A column exists in `packages/shared/schemas/lead.json` (regenerated
 *     from `packages/hermes-dist/plugins/lead-capture/schema.py`) but not in
 *     the TS `Lead` interface.
 *   - The TS interface declares a field that does not exist in SQLite.
 *   - Enum values (kanban_column, temperature, urgency, platform,
 *     column_source) diverge between Python and TS.
 *
 * The JSON Schema artifact is regenerated by running:
 *   PYTHONPATH=packages/hermes-dist/plugins/lead-capture python3 -c \
 *     "from schema import emit_json_schema; import json; \
 *      print(json.dumps(emit_json_schema()))" \
 *     > packages/shared/schemas/lead.json
 * (or by running `tests/contract/test_emit_schema.py`).
 *
 * If this test fails, do NOT edit it — fix the divergence on whichever side
 * changed last.
 */
import { describe, expect, it } from "vitest";
import schemaJson from "@hermes-leads/shared/schemas/lead.json";
import {
  KANBAN_COLUMNS,
  VALID_KANBAN_COLUMNS,
  VALID_TEMPERATURES,
  VALID_URGENCIES,
  VALID_PLATFORMS,
  VALID_COLUMN_SOURCES,
  type Lead,
} from "@hermes-leads/shared";

interface ColumnDef {
  name: string;
  sqlite_type: string;
  nullable: boolean;
}

interface SchemaJson {
  $schema: string;
  tables: {
    leads: { columns: ColumnDef[]; unique: string[][] };
    lead_events: { columns: ColumnDef[]; unique: string[][] };
  };
  enums: {
    kanban_columns: string[];
    temperatures: string[];
    urgencies: string[];
    platforms: string[];
    column_sources: string[];
  };
}

const schema = schemaJson as SchemaJson;

describe("lead schema contract (Python ↔ TypeScript)", () => {
  const sqliteLeadsColumns = schema.tables.leads.columns.map((c) => c.name);

  // The TS interface is structural — we can't enumerate keys at runtime
  // without an instance, so we define a representative row and assert that
  // every SQLite column has a matching property on it.
  const sampleLead: Lead = {
    id: "x",
    user_id: "u",
    session_id: null,
    platform: "telegram",
    name: null,
    email: null,
    phone: null,
    interest: null,
    urgency: "medium",
    temperature: "tibio",
    kanban_column: "tibio",
    position: 0,
    summary: null,
    notes: null,
    last_user_message: null,
    last_assistant_message: null,
    raw_extraction: null,
    last_extracted_at: null,
    column_source: "llm",
    column_locked_at: null,
    manual_override: 0,
    created_at: "1970-01-01T00:00:00Z",
    updated_at: "1970-01-01T00:00:00Z",
  };

  it("every SQLite column is present on the TS Lead interface", () => {
    const tsKeys = new Set(Object.keys(sampleLead));
    const missing = sqliteLeadsColumns.filter((c) => !tsKeys.has(c));
    expect(
      missing,
      `SQLite columns missing from TS Lead: ${missing.join(", ")}. ` +
        `Add them to packages/shared/src/types/lead.ts.`
    ).toEqual([]);
  });

  it("every TS Lead field exists in SQLite", () => {
    const sqliteSet = new Set(sqliteLeadsColumns);
    const extra = Object.keys(sampleLead).filter((k) => !sqliteSet.has(k));
    expect(
      extra,
      `TS Lead fields missing from SQLite: ${extra.join(", ")}. ` +
        `Either add the column to schema.py + db.py, or drop it from Lead.`
    ).toEqual([]);
  });

  it("kanban_column enums match", () => {
    // KANBAN_COLUMNS is the extractor-assigned subset; VALID_KANBAN_COLUMNS
    // adds `descartado` (manual-only). The Python schema's kanban_columns
    // is the full set (with descartado) — see schema.py.
    expect([...VALID_KANBAN_COLUMNS].sort()).toEqual(
      [...schema.enums.kanban_columns].sort()
    );
    // And KANBAN_COLUMNS must be exactly the schema's list minus `descartado`.
    expect([...KANBAN_COLUMNS].sort()).toEqual(
      [...schema.enums.kanban_columns]
        .filter((c) => c !== "descartado")
        .sort()
    );
  });

  it("temperature enums match", () => {
    expect([...VALID_TEMPERATURES].sort()).toEqual(
      [...schema.enums.temperatures].sort()
    );
  });

  it("urgency enums match", () => {
    expect([...VALID_URGENCIES].sort()).toEqual(
      [...schema.enums.urgencies].sort()
    );
  });

  it("platform enums match", () => {
    expect([...VALID_PLATFORMS].sort()).toEqual(
      [...schema.enums.platforms].sort()
    );
  });

  it("column_source enums match", () => {
    expect([...VALID_COLUMN_SOURCES].sort()).toEqual(
      [...schema.enums.column_sources].sort()
    );
  });

  it("every table in the JSON Schema is non-empty", () => {
    expect(schema.tables.leads.columns.length).toBeGreaterThan(0);
    expect(schema.tables.lead_events.columns.length).toBeGreaterThan(0);
  });
});
